### ISSUE TITLE
Add small variation of an empty state

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#297] opened 2020-10-12 15:15 UTC
Add a small (xs) variation of an empty state in a card to a template. 

Mocks available here https://marvelapp.com/prototype/7c5cdhd/screen/72928590
HTML available here https://www.patternfly.org/v4/components/empty-state/html#extra-small

- Create artboards to for the "Empty state" page in a template

**Be sure you added a Core-only label to these artboards.**

**Comment by mmenestr** [comment] 2020-10-13 20:57
Duplicate of https://github.com/patternfly/patternfly-design-kit/issues/295, so closing

**Closed by mmenestr** 2020-10-13 20:57 UTC
Labels: template
